package model;

public class TerrainMap extends Map {
	protected TERRAINTYPE[][] map;
	
	public TerrainMap() {
		super();
		map = new TERRAINTYPE[][] {
				new TERRAINTYPE[] {TERRAINTYPE.WATER,TERRAINTYPE.WATER,TERRAINTYPE.WATER,TERRAINTYPE.WATER,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.ROCK,TERRAINTYPE.ROCK},
				new TERRAINTYPE[] {TERRAINTYPE.WATER,TERRAINTYPE.WATER,TERRAINTYPE.WATER,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.ROCK,TERRAINTYPE.ROCK},
				new TERRAINTYPE[] {TERRAINTYPE.WATER,TERRAINTYPE.WATER,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.ROCK,TERRAINTYPE.ROCK,TERRAINTYPE.ROCK},
				new TERRAINTYPE[] {TERRAINTYPE.WATER,TERRAINTYPE.WATER,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.ROCK,TERRAINTYPE.ROCK,TERRAINTYPE.ROCK},
				new TERRAINTYPE[] {TERRAINTYPE.WATER,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.ROCK,TERRAINTYPE.ROCK,TERRAINTYPE.ROCK},
				new TERRAINTYPE[] {TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.ROCK,TERRAINTYPE.ROCK},
				new TERRAINTYPE[] {TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.ROCK},
				new TERRAINTYPE[] {TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.FIELD,TERRAINTYPE.ROCK},
		};
	}
	
	public TERRAINTYPE getField(int x, int y) {
		if((x >= 0 && x < width) && (y>=0 && y < height))
			return map[x][y];
		else return null;
	}
}
